# Generated by Django 5.1.4 on 2024-12-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_stock_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_id',
        ),
    ]
