version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: stockDB           
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: 231196      
    volumes:
      - pgdata:/var/lib/postgresql/data  
    ports:
      - "5432:5432"  # Permet l'accès à la base de données depuis l'hôte
    networks:
      - django-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db  
    networks:
      - django-network

volumes:
  pgdata:

networks:
  django-network:
    driver: bridge
